name: Publish package

on:
  release:
    types: [published] # run when a new release is published

env:
  name: ChebsNecromancy
  jsonf: manifest.json

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get clean version
        run: |
          echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
      - name: Check that version matches
        run: |
          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./ -name ${{env.jsonf}}))" != "${{ env.cleanVersion }}" ]]; then
            echo "::debug::${{env.cleanVersion}}"
            echo "::debug::$(cat $(find ./ -name ${{env.jsonf}} ))"
            echo "::error::Version in ${{env.jsonf}} does not match tag version"
            exit 1
          fi
  publish:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v3
      - name: Upload Thunderstore Package
        uses: GreenTF/upload-thunderstore-package@v3.1
        with:
          community: Valheim
          namespace: ChebGonaz
          name: ${{ env.name }}
          version: ${{ github.ref_name }} # This is the tag that was created in the release
          description: Cheb's Necromancy adds Necromancy to Valheim via craftable wands and structures. Minions will follow you, guard your base, and perform menial tasks.
          token: ${{ secrets.TS_KEY }} 
          #wrap: mods/${{ github.repository_owner }}.${{ env.name }} # This will wrap your Author.ModName folder in a mods/ folder before publishing
          deps: "ValheimModding-Jotunn-2.11.2" # dependencies separated by spaces
          categories: "Mods" # categories separated by spaces
          file: ${{ github.event.release.assets[0].name }} # Use the first asset from the release
